import type { Prop } from "../lib/types";

const now = () => Date.now();

export function seedSlate(): Prop[] {
  const t = now();
  return [
    {
      id: "nba-luka-pts",
      sport: "NBA",
      player: "Luka Dončić",
      team: "LAL",
      opponent: "BOS",
      position: "PG",
      stat: "points",
      statLabel: "Points",
      line: 28.5,
      openingLine: 29.5,
      liveStat: 16,
      gameStatus: "live",
      clock: "Q2 4:18",
      updatedAt: t,
    },
    {
      id: "nba-tatum-pts",
      sport: "NBA",
      player: "Jayson Tatum",
      team: "BOS",
      opponent: "LAL",
      position: "SF",
      stat: "points",
      statLabel: "Points",
      line: 26.5,
      openingLine: 26.5,
      liveStat: 12,
      gameStatus: "live",
      clock: "Q2 4:18",
      updatedAt: t,
    },
    {
      id: "nba-ad-reb",
      sport: "NBA",
      player: "Anthony Davis",
      team: "DAL",
      opponent: "LAL",
      position: "C",
      stat: "rebounds",
      statLabel: "Rebounds",
      line: 11.5,
      openingLine: 11.5,
      liveStat: 7,
      gameStatus: "live",
      clock: "Q2 4:18",
      updatedAt: t,
    },
    {
      id: "nba-white-ast",
      sport: "NBA",
      player: "Derrick White",
      team: "BOS",
      opponent: "LAL",
      position: "SG",
      stat: "assists",
      statLabel: "Assists",
      line: 5.5,
      openingLine: 5.5,
      liveStat: 3,
      gameStatus: "live",
      clock: "Q2 4:18",
      updatedAt: t,
    },
    {
      id: "nba-jokic-pts",
      sport: "NBA",
      player: "Nikola Jokić",
      team: "DEN",
      opponent: "PHX",
      position: "C",
      stat: "points",
      statLabel: "Points",
      line: 27.5,
      openingLine: 27.5,
      liveStat: null,
      gameStatus: "scheduled",
      clock: "8:10 PM ET",
      updatedAt: t,
    },
    {
      id: "nba-jokic-reb",
      sport: "NBA",
      player: "Nikola Jokić",
      team: "DEN",
      opponent: "PHX",
      position: "C",
      stat: "rebounds",
      statLabel: "Rebounds",
      line: 12.5,
      openingLine: 12.5,
      liveStat: null,
      gameStatus: "scheduled",
      clock: "8:10 PM ET",
      updatedAt: t,
    },
    {
      id: "nba-booker-pts",
      sport: "NBA",
      player: "Devin Booker",
      team: "PHX",
      opponent: "DEN",
      position: "SG",
      stat: "points",
      statLabel: "Points",
      line: 25.5,
      openingLine: 24.5,
      liveStat: null,
      gameStatus: "scheduled",
      clock: "8:10 PM ET",
      updatedAt: t,
    },
    {
      id: "nba-kd-threes",
      sport: "NBA",
      player: "Kevin Durant",
      team: "HOU",
      opponent: "GSW",
      position: "SF",
      stat: "threes",
      statLabel: "3-Pointers",
      line: 2.5,
      openingLine: 2.5,
      liveStat: 1,
      gameStatus: "live",
      clock: "Q1 2:40",
      updatedAt: t,
    },
    {
      id: "nba-curry-threes",
      sport: "NBA",
      player: "Stephen Curry",
      team: "GSW",
      opponent: "HOU",
      position: "PG",
      stat: "threes",
      statLabel: "3-Pointers",
      line: 4.5,
      openingLine: 4.5,
      liveStat: 2,
      gameStatus: "live",
      clock: "Q1 2:40",
      updatedAt: t,
    },
    {
      id: "nba-edwards-pts",
      sport: "NBA",
      player: "Anthony Edwards",
      team: "MIN",
      opponent: "NYK",
      position: "SG",
      stat: "points",
      statLabel: "Points",
      line: 27.5,
      openingLine: 28.5,
      liveStat: null,
      gameStatus: "scheduled",
      clock: "9:30 PM ET",
      updatedAt: t,
    },
    {
      id: "nfl-mahomes-pass",
      sport: "NFL",
      player: "Patrick Mahomes",
      team: "KC",
      opponent: "BUF",
      position: "QB",
      stat: "pass_yds",
      statLabel: "Pass Yds",
      line: 268.5,
      openingLine: 272.5,
      liveStat: 142,
      gameStatus: "live",
      clock: "Q2 11:04",
      updatedAt: t,
    },
    {
      id: "nfl-allen-pass",
      sport: "NFL",
      player: "Josh Allen",
      team: "BUF",
      opponent: "KC",
      position: "QB",
      stat: "pass_yds",
      statLabel: "Pass Yds",
      line: 254.5,
      openingLine: 251.5,
      liveStat: 118,
      gameStatus: "live",
      clock: "Q2 11:04",
      updatedAt: t,
    },
    {
      id: "nfl-cmc-rush",
      sport: "NFL",
      player: "Christian McCaffrey",
      team: "SF",
      opponent: "SEA",
      position: "RB",
      stat: "rush_yds",
      statLabel: "Rush Yds",
      line: 78.5,
      openingLine: 78.5,
      liveStat: null,
      gameStatus: "scheduled",
      clock: "Sun 4:25 PM",
      updatedAt: t,
    },
    {
      id: "nfl-kupp-rec",
      sport: "NFL",
      player: "Cooper Kupp",
      team: "SEA",
      opponent: "SF",
      position: "WR",
      stat: "receptions",
      statLabel: "Receptions",
      line: 6.5,
      openingLine: 6.5,
      liveStat: null,
      gameStatus: "scheduled",
      clock: "Sun 4:25 PM",
      updatedAt: t,
    },
    {
      id: "nfl-jefferson-rec",
      sport: "NFL",
      player: "Justin Jefferson",
      team: "MIN",
      opponent: "GB",
      position: "WR",
      stat: "receptions",
      statLabel: "Receptions",
      line: 7.5,
      openingLine: 7.5,
      liveStat: 4,
      gameStatus: "final",
      clock: "Final",
      updatedAt: t,
    },
    {
      id: "nfl-hurts-rush",
      sport: "NFL",
      player: "Jalen Hurts",
      team: "PHI",
      opponent: "DAL",
      position: "QB",
      stat: "rush_yds",
      statLabel: "Rush Yds",
      line: 36.5,
      openingLine: 34.5,
      liveStat: 22,
      gameStatus: "live",
      clock: "Q3 8:51",
      updatedAt: t,
    },
  ];
}
