import { elapsedAt } from "../lib/sim";
import type { GameStatus, Prop, Sport } from "../lib/types";

/**
 * Demo slate. Props are grouped into games so every card in a game shares one
 * clock, and stat accumulation has something to be paced against.
 *
 * Players are real; every line, projection and score here is invented.
 */

export type GameSeed = {
  id: string;
  sport: Sport;
  status: GameStatus;
  /** Simulated seconds played. */
  elapsedSec: number;
  /** Simulated seconds until tip-off / kickoff, for scheduled games. */
  startsInSec: number;
  /** What the card shows before the game starts. */
  startLabel: string;
};

/** Everything the engine does not derive from the game clock. */
export type PropSeed = Omit<Prop, "liveStat" | "clock" | "gameStatus" | "updatedAt">;

export function seedGames(): GameSeed[] {
  return [
    {
      id: "nba-lal-bos",
      sport: "NBA",
      status: "live",
      elapsedSec: elapsedAt("NBA", 2, 4, 18),
      startsInSec: 0,
      startLabel: "7:30 PM ET",
    },
    {
      id: "nba-hou-gsw",
      sport: "NBA",
      status: "live",
      elapsedSec: elapsedAt("NBA", 1, 2, 40),
      startsInSec: 0,
      startLabel: "8:00 PM ET",
    },
    {
      id: "nba-dal-mem",
      sport: "NBA",
      status: "live",
      elapsedSec: elapsedAt("NBA", 3, 7, 5),
      startsInSec: 0,
      startLabel: "7:00 PM ET",
    },
    {
      id: "nba-den-phx",
      sport: "NBA",
      status: "scheduled",
      elapsedSec: 0,
      startsInSec: 210,
      startLabel: "8:10 PM ET",
    },
    {
      id: "nba-min-nyk",
      sport: "NBA",
      status: "scheduled",
      elapsedSec: 0,
      startsInSec: 690,
      startLabel: "9:30 PM ET",
    },
    {
      id: "nfl-kc-buf",
      sport: "NFL",
      status: "live",
      elapsedSec: elapsedAt("NFL", 2, 11, 4),
      startsInSec: 0,
      startLabel: "Sun 1:00 PM",
    },
    {
      id: "nfl-phi-dal",
      sport: "NFL",
      status: "live",
      elapsedSec: elapsedAt("NFL", 3, 8, 51),
      startsInSec: 0,
      startLabel: "Sun 1:00 PM",
    },
    {
      id: "nfl-sf-sea",
      sport: "NFL",
      status: "scheduled",
      elapsedSec: 0,
      startsInSec: 420,
      startLabel: "Sun 4:25 PM",
    },
    {
      id: "nfl-min-gb",
      sport: "NFL",
      status: "final",
      elapsedSec: 3600,
      startsInSec: 0,
      startLabel: "Sun 1:00 PM",
    },
  ];
}

export function seedSlate(): PropSeed[] {
  return [
    {
      id: "nba-luka-pts",
      gameId: "nba-lal-bos",
      sport: "NBA",
      player: "Luka Dončić",
      team: "LAL",
      opponent: "BOS",
      position: "PG",
      stat: "points",
      statLabel: "Points",
      line: 28.5,
      openingLine: 29.5,
    },
    {
      id: "nba-tatum-pts",
      gameId: "nba-lal-bos",
      sport: "NBA",
      player: "Jayson Tatum",
      team: "BOS",
      opponent: "LAL",
      position: "SF",
      stat: "points",
      statLabel: "Points",
      line: 26.5,
      openingLine: 26.5,
    },
    {
      id: "nba-white-ast",
      gameId: "nba-lal-bos",
      sport: "NBA",
      player: "Derrick White",
      team: "BOS",
      opponent: "LAL",
      position: "SG",
      stat: "assists",
      statLabel: "Assists",
      line: 5.5,
      openingLine: 5.5,
    },
    {
      id: "nba-ad-reb",
      gameId: "nba-dal-mem",
      sport: "NBA",
      player: "Anthony Davis",
      team: "DAL",
      opponent: "MEM",
      position: "C",
      stat: "rebounds",
      statLabel: "Rebounds",
      line: 11.5,
      openingLine: 11.5,
    },
    {
      id: "nba-kd-threes",
      gameId: "nba-hou-gsw",
      sport: "NBA",
      player: "Kevin Durant",
      team: "HOU",
      opponent: "GSW",
      position: "SF",
      stat: "threes",
      statLabel: "3-Pointers",
      line: 2.5,
      openingLine: 2.5,
    },
    {
      id: "nba-curry-threes",
      gameId: "nba-hou-gsw",
      sport: "NBA",
      player: "Stephen Curry",
      team: "GSW",
      opponent: "HOU",
      position: "PG",
      stat: "threes",
      statLabel: "3-Pointers",
      line: 4.5,
      openingLine: 4.5,
    },
    {
      id: "nba-jokic-pts",
      gameId: "nba-den-phx",
      sport: "NBA",
      player: "Nikola Jokić",
      team: "DEN",
      opponent: "PHX",
      position: "C",
      stat: "points",
      statLabel: "Points",
      line: 27.5,
      openingLine: 27.5,
    },
    {
      id: "nba-jokic-reb",
      gameId: "nba-den-phx",
      sport: "NBA",
      player: "Nikola Jokić",
      team: "DEN",
      opponent: "PHX",
      position: "C",
      stat: "rebounds",
      statLabel: "Rebounds",
      line: 12.5,
      openingLine: 12.5,
    },
    {
      id: "nba-booker-pts",
      gameId: "nba-den-phx",
      sport: "NBA",
      player: "Devin Booker",
      team: "PHX",
      opponent: "DEN",
      position: "SG",
      stat: "points",
      statLabel: "Points",
      line: 25.5,
      openingLine: 24.5,
    },
    {
      id: "nba-edwards-pts",
      gameId: "nba-min-nyk",
      sport: "NBA",
      player: "Anthony Edwards",
      team: "MIN",
      opponent: "NYK",
      position: "SG",
      stat: "points",
      statLabel: "Points",
      line: 27.5,
      openingLine: 28.5,
    },
    {
      id: "nfl-mahomes-pass",
      gameId: "nfl-kc-buf",
      sport: "NFL",
      player: "Patrick Mahomes",
      team: "KC",
      opponent: "BUF",
      position: "QB",
      stat: "pass_yds",
      statLabel: "Pass Yds",
      line: 268.5,
      openingLine: 272.5,
    },
    {
      id: "nfl-allen-pass",
      gameId: "nfl-kc-buf",
      sport: "NFL",
      player: "Josh Allen",
      team: "BUF",
      opponent: "KC",
      position: "QB",
      stat: "pass_yds",
      statLabel: "Pass Yds",
      line: 254.5,
      openingLine: 251.5,
    },
    {
      id: "nfl-hurts-rush",
      gameId: "nfl-phi-dal",
      sport: "NFL",
      player: "Jalen Hurts",
      team: "PHI",
      opponent: "DAL",
      position: "QB",
      stat: "rush_yds",
      statLabel: "Rush Yds",
      line: 36.5,
      openingLine: 34.5,
    },
    {
      id: "nfl-cmc-rush",
      gameId: "nfl-sf-sea",
      sport: "NFL",
      player: "Christian McCaffrey",
      team: "SF",
      opponent: "SEA",
      position: "RB",
      stat: "rush_yds",
      statLabel: "Rush Yds",
      line: 78.5,
      openingLine: 78.5,
    },
    {
      id: "nfl-kupp-rec",
      gameId: "nfl-sf-sea",
      sport: "NFL",
      player: "Cooper Kupp",
      team: "SEA",
      opponent: "SF",
      position: "WR",
      stat: "receptions",
      statLabel: "Receptions",
      line: 6.5,
      openingLine: 6.5,
    },
    {
      id: "nfl-jefferson-rec",
      gameId: "nfl-min-gb",
      sport: "NFL",
      player: "Justin Jefferson",
      team: "MIN",
      opponent: "GB",
      position: "WR",
      stat: "receptions",
      statLabel: "Receptions",
      line: 7.5,
      openingLine: 7.5,
    },
  ];
}
